language: ruby
rvm:
  - 2.1.2
before_script:
  - "cp config/database.yml.example config/database.yml"
  - "psql -c 'create database opencongress_test;' -U postgres"
  - "bundle exec rake db:migrate db:test:prepare"
script: "echo 'no tests for now'"
notifications:
  email:
    - hsandler@sunlightfoundation.com
    - spaceman@sunlightfoundation.com
    - beef.salad@sunlightfoundation.com